var masterList = [
  {
    "term": "accessibility",
    "accessibility": 0,
    "acoustics": 5,
    "aerospace": 0,
    "artificial intelligence": 9,
    "assembly": 1,
    "augmented reality": 83,
    "automation": 5,
    "automobiles": 1,
    "color": 1,
    "computer vision": 3,
    "computing": 1,
    "construction": 0,
    "control": 13,
    "controllers": 0,
    "data modeling": 2,
    "display technology": 8,
    "education": 2,
    "emergency management": 0,
    "energy management": 2,
    "entertainment": 10,
    "food and agriculture": 0,
    "handheld computing": 3,
    "hardware": 3,
    "holography": 0,
    "human computer interaction": 38,
    "human factors": 29,
    "human resources": 0,
    "image processing": 2,
    "information systems": 1,
    "infrastructure": 2,
    "lighting": 0,
    "location based services": 5,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 1,
    "marketing": 0,
    "materials": 2,
    "mathematics": 1,
    "medical applications": 61,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 13,
    "operating system": 3,
    "optics": 3,
    "physics": 1,
    "policy": 1,
    "programming language": 1,
    "quality management": 1,
    "risk": 0,
    "robotics": 6,
    "safety": 6,
    "security": 1,
    "sensors": 5,
    "simulation": 4,
    "sustainability": 2,
    "training": 6,
    "transportation": 2,
    "virtual reality": 18,
    "wearables": 20,
    "web services": 0,
    "": ""
  },
  {
    "term": "acoustics",
    "accessibility": 5,
    "acoustics": 0,
    "aerospace": 2,
    "artificial intelligence": 5,
    "assembly": 1,
    "augmented reality": 41,
    "automation": 0,
    "automobiles": 0,
    "color": 1,
    "computer vision": 0,
    "computing": 2,
    "construction": 2,
    "control": 2,
    "controllers": 2,
    "data modeling": 2,
    "display technology": 8,
    "education": 3,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 5,
    "food and agriculture": 1,
    "handheld computing": 3,
    "hardware": 0,
    "holography": 1,
    "human computer interaction": 26,
    "human factors": 10,
    "human resources": 0,
    "image processing": 3,
    "information systems": 0,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 4,
    "machinery": 2,
    "magnetics": 1,
    "maintenance": 0,
    "manufacturing": 1,
    "marketing": 0,
    "materials": 2,
    "mathematics": 5,
    "medical applications": 6,
    "military": 1,
    "mixed reality": 1,
    "mobile computing": 8,
    "operating system": 0,
    "optics": 0,
    "physics": 5,
    "policy": 0,
    "programming language": 0,
    "quality management": 2,
    "risk": 0,
    "robotics": 3,
    "safety": 0,
    "security": 2,
    "sensors": 4,
    "simulation": 1,
    "sustainability": 1,
    "training": 1,
    "transportation": 1,
    "virtual reality": 9,
    "wearables": 6,
    "web services": 0,
    "": ""
  },
  {
    "term": "aerospace",
    "accessibility": 0,
    "acoustics": 2,
    "aerospace": 0,
    "artificial intelligence": 3,
    "assembly": 2,
    "augmented reality": 29,
    "automation": 3,
    "automobiles": 1,
    "color": 0,
    "computer vision": 2,
    "computing": 1,
    "construction": 0,
    "control": 4,
    "controllers": 1,
    "data modeling": 2,
    "display technology": 6,
    "education": 1,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 3,
    "food and agriculture": 1,
    "handheld computing": 1,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 14,
    "human factors": 4,
    "human resources": 0,
    "image processing": 5,
    "information systems": 2,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 3,
    "machinery": 1,
    "magnetics": 0,
    "maintenance": 3,
    "manufacturing": 6,
    "marketing": 3,
    "materials": 2,
    "mathematics": 3,
    "medical applications": 5,
    "military": 0,
    "mixed reality": 2,
    "mobile computing": 7,
    "operating system": 0,
    "optics": 0,
    "physics": 5,
    "policy": 0,
    "programming language": 0,
    "quality management": 4,
    "risk": 0,
    "robotics": 6,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 0,
    "sustainability": 0,
    "training": 3,
    "transportation": 2,
    "virtual reality": 6,
    "wearables": 7,
    "web services": 1,
    "": ""
  },
  {
    "term": "artificial intelligence",
    "accessibility": 9,
    "acoustics": 5,
    "aerospace": 3,
    "artificial intelligence": 0,
    "assembly": 3,
    "augmented reality": 170,
    "automation": 10,
    "automobiles": 2,
    "color": 1,
    "computer vision": 27,
    "computing": 6,
    "construction": 2,
    "control": 5,
    "controllers": 2,
    "data modeling": 16,
    "display technology": 22,
    "education": 12,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 9,
    "food and agriculture": 3,
    "handheld computing": 8,
    "hardware": 0,
    "holography": 2,
    "human computer interaction": 98,
    "human factors": 32,
    "human resources": 2,
    "image processing": 32,
    "information systems": 3,
    "infrastructure": 9,
    "lighting": 0,
    "location based services": 7,
    "machinery": 3,
    "magnetics": 1,
    "maintenance": 3,
    "manufacturing": 20,
    "marketing": 4,
    "materials": 7,
    "mathematics": 33,
    "medical applications": 42,
    "military": 1,
    "mixed reality": 3,
    "mobile computing": 22,
    "operating system": 1,
    "optics": 3,
    "physics": 4,
    "policy": 2,
    "programming language": 2,
    "quality management": 12,
    "risk": 0,
    "robotics": 8,
    "safety": 0,
    "security": 1,
    "sensors": 6,
    "simulation": 4,
    "sustainability": 4,
    "training": 8,
    "transportation": 6,
    "virtual reality": 29,
    "wearables": 24,
    "web services": 2,
    "": ""
  },
  {
    "term": "assembly",
    "accessibility": 1,
    "acoustics": 1,
    "aerospace": 2,
    "artificial intelligence": 3,
    "assembly": 0,
    "augmented reality": 24,
    "automation": 1,
    "automobiles": 4,
    "color": 0,
    "computer vision": 2,
    "computing": 1,
    "construction": 0,
    "control": 4,
    "controllers": 0,
    "data modeling": 0,
    "display technology": 1,
    "education": 0,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 1,
    "food and agriculture": 1,
    "handheld computing": 0,
    "hardware": 1,
    "holography": 0,
    "human computer interaction": 7,
    "human factors": 1,
    "human resources": 1,
    "image processing": 3,
    "information systems": 1,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 0,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 2,
    "manufacturing": 17,
    "marketing": 0,
    "materials": 0,
    "mathematics": 1,
    "medical applications": 0,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 5,
    "operating system": 0,
    "optics": 0,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 2,
    "risk": 0,
    "robotics": 3,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 1,
    "sustainability": 0,
    "training": 6,
    "transportation": 1,
    "virtual reality": 4,
    "wearables": 3,
    "web services": 0,
    "": ""
  },
  {
    "term": "augmented reality",
    "accessibility": 83,
    "acoustics": 41,
    "aerospace": 29,
    "artificial intelligence": 170,
    "assembly": 24,
    "augmented reality": 0,
    "automation": 48,
    "automobiles": 24,
    "color": 9,
    "computer vision": 85,
    "computing": 81,
    "construction": 14,
    "control": 92,
    "controllers": 22,
    "data modeling": 73,
    "display technology": 217,
    "education": 75,
    "emergency management": 5,
    "energy management": 13,
    "entertainment": 105,
    "food and agriculture": 20,
    "handheld computing": 63,
    "hardware": 15,
    "holography": 29,
    "human computer interaction": 654,
    "human factors": 297,
    "human resources": 11,
    "image processing": 133,
    "information systems": 22,
    "infrastructure": 46,
    "lighting": 10,
    "location based services": 56,
    "machinery": 44,
    "magnetics": 8,
    "maintenance": 24,
    "manufacturing": 125,
    "marketing": 27,
    "materials": 84,
    "mathematics": 65,
    "medical applications": 279,
    "military": 9,
    "mixed reality": 32,
    "mobile computing": 212,
    "operating system": 8,
    "optics": 48,
    "physics": 37,
    "policy": 3,
    "programming language": 18,
    "quality management": 49,
    "risk": 3,
    "robotics": 111,
    "safety": 16,
    "security": 23,
    "sensors": 37,
    "simulation": 40,
    "sustainability": 33,
    "training": 49,
    "transportation": 38,
    "virtual reality": 182,
    "wearables": 307,
    "web services": 42,
    "": ""
  },
  {
    "term": "automation",
    "accessibility": 5,
    "acoustics": 0,
    "aerospace": 3,
    "artificial intelligence": 10,
    "assembly": 1,
    "augmented reality": 48,
    "automation": 0,
    "automobiles": 7,
    "color": 0,
    "computer vision": 4,
    "computing": 1,
    "construction": 2,
    "control": 6,
    "controllers": 0,
    "data modeling": 3,
    "display technology": 15,
    "education": 2,
    "emergency management": 0,
    "energy management": 1,
    "entertainment": 3,
    "food and agriculture": 0,
    "handheld computing": 1,
    "hardware": 1,
    "holography": 0,
    "human computer interaction": 20,
    "human factors": 17,
    "human resources": 0,
    "image processing": 6,
    "information systems": 2,
    "infrastructure": 12,
    "lighting": 0,
    "location based services": 0,
    "machinery": 3,
    "magnetics": 2,
    "maintenance": 1,
    "manufacturing": 5,
    "marketing": 1,
    "materials": 3,
    "mathematics": 1,
    "medical applications": 4,
    "military": 2,
    "mixed reality": 0,
    "mobile computing": 8,
    "operating system": 0,
    "optics": 0,
    "physics": 2,
    "policy": 0,
    "programming language": 0,
    "quality management": 4,
    "risk": 1,
    "robotics": 5,
    "safety": 1,
    "security": 0,
    "sensors": 1,
    "simulation": 3,
    "sustainability": 1,
    "training": 1,
    "transportation": 8,
    "virtual reality": 10,
    "wearables": 6,
    "web services": 0,
    "": ""
  },
  {
    "term": "automobiles",
    "accessibility": 1,
    "acoustics": 0,
    "aerospace": 1,
    "artificial intelligence": 2,
    "assembly": 4,
    "augmented reality": 24,
    "automation": 7,
    "automobiles": 0,
    "color": 1,
    "computer vision": 0,
    "computing": 1,
    "construction": 0,
    "control": 3,
    "controllers": 0,
    "data modeling": 0,
    "display technology": 8,
    "education": 0,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 0,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 8,
    "human factors": 7,
    "human resources": 1,
    "image processing": 0,
    "information systems": 1,
    "infrastructure": 3,
    "lighting": 0,
    "location based services": 1,
    "machinery": 1,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 4,
    "marketing": 1,
    "materials": 1,
    "mathematics": 0,
    "medical applications": 1,
    "military": 0,
    "mixed reality": 2,
    "mobile computing": 0,
    "operating system": 0,
    "optics": 2,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 2,
    "risk": 0,
    "robotics": 0,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 1,
    "sustainability": 1,
    "training": 2,
    "transportation": 8,
    "virtual reality": 4,
    "wearables": 1,
    "web services": 0,
    "": ""
  },
  {
    "term": "color",
    "accessibility": 1,
    "acoustics": 1,
    "aerospace": 0,
    "artificial intelligence": 1,
    "assembly": 0,
    "augmented reality": 9,
    "automation": 0,
    "automobiles": 1,
    "color": 0,
    "computer vision": 0,
    "computing": 1,
    "construction": 0,
    "control": 1,
    "controllers": 0,
    "data modeling": 0,
    "display technology": 3,
    "education": 0,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 2,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 5,
    "human factors": 4,
    "human resources": 0,
    "image processing": 0,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 2,
    "location based services": 0,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 0,
    "marketing": 0,
    "materials": 2,
    "mathematics": 0,
    "medical applications": 0,
    "military": 0,
    "mixed reality": 1,
    "mobile computing": 0,
    "operating system": 0,
    "optics": 1,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 0,
    "risk": 0,
    "robotics": 0,
    "safety": 1,
    "security": 0,
    "sensors": 0,
    "simulation": 0,
    "sustainability": 0,
    "training": 0,
    "transportation": 0,
    "virtual reality": 2,
    "wearables": 4,
    "web services": 0,
    "": ""
  },
  {
    "term": "computer vision",
    "accessibility": 3,
    "acoustics": 0,
    "aerospace": 2,
    "artificial intelligence": 27,
    "assembly": 2,
    "augmented reality": 85,
    "automation": 4,
    "automobiles": 0,
    "color": 0,
    "computer vision": 0,
    "computing": 7,
    "construction": 2,
    "control": 6,
    "controllers": 0,
    "data modeling": 3,
    "display technology": 28,
    "education": 3,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 5,
    "food and agriculture": 3,
    "handheld computing": 4,
    "hardware": 0,
    "holography": 1,
    "human computer interaction": 39,
    "human factors": 10,
    "human resources": 2,
    "image processing": 36,
    "information systems": 0,
    "infrastructure": 2,
    "lighting": 1,
    "location based services": 3,
    "machinery": 5,
    "magnetics": 1,
    "maintenance": 3,
    "manufacturing": 9,
    "marketing": 2,
    "materials": 2,
    "mathematics": 19,
    "medical applications": 10,
    "military": 0,
    "mixed reality": 2,
    "mobile computing": 14,
    "operating system": 0,
    "optics": 0,
    "physics": 3,
    "policy": 0,
    "programming language": 1,
    "quality management": 2,
    "risk": 0,
    "robotics": 10,
    "safety": 0,
    "security": 1,
    "sensors": 8,
    "simulation": 1,
    "sustainability": 0,
    "training": 1,
    "transportation": 3,
    "virtual reality": 11,
    "wearables": 14,
    "web services": 0,
    "": ""
  },
  {
    "term": "computing",
    "accessibility": 1,
    "acoustics": 2,
    "aerospace": 1,
    "artificial intelligence": 6,
    "assembly": 1,
    "augmented reality": 81,
    "automation": 1,
    "automobiles": 1,
    "color": 1,
    "computer vision": 7,
    "computing": 0,
    "construction": 2,
    "control": 5,
    "controllers": 1,
    "data modeling": 5,
    "display technology": 8,
    "education": 6,
    "emergency management": 1,
    "energy management": 0,
    "entertainment": 10,
    "food and agriculture": 0,
    "handheld computing": 1,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 47,
    "human factors": 17,
    "human resources": 2,
    "image processing": 10,
    "information systems": 0,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 3,
    "machinery": 4,
    "magnetics": 0,
    "maintenance": 2,
    "manufacturing": 8,
    "marketing": 0,
    "materials": 2,
    "mathematics": 3,
    "medical applications": 9,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 16,
    "operating system": 0,
    "optics": 2,
    "physics": 1,
    "policy": 0,
    "programming language": 2,
    "quality management": 3,
    "risk": 0,
    "robotics": 5,
    "safety": 1,
    "security": 1,
    "sensors": 0,
    "simulation": 0,
    "sustainability": 2,
    "training": 5,
    "transportation": 1,
    "virtual reality": 15,
    "wearables": 15,
    "web services": 7,
    "": ""
  },
  {
    "term": "construction",
    "accessibility": 0,
    "acoustics": 2,
    "aerospace": 0,
    "artificial intelligence": 2,
    "assembly": 0,
    "augmented reality": 14,
    "automation": 2,
    "automobiles": 0,
    "color": 0,
    "computer vision": 2,
    "computing": 2,
    "construction": 0,
    "control": 1,
    "controllers": 0,
    "data modeling": 3,
    "display technology": 1,
    "education": 1,
    "emergency management": 0,
    "energy management": 1,
    "entertainment": 1,
    "food and agriculture": 0,
    "handheld computing": 2,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 11,
    "human factors": 2,
    "human resources": 0,
    "image processing": 2,
    "information systems": 1,
    "infrastructure": 2,
    "lighting": 0,
    "location based services": 0,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 4,
    "marketing": 1,
    "materials": 1,
    "mathematics": 2,
    "medical applications": 1,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 2,
    "operating system": 0,
    "optics": 0,
    "physics": 1,
    "policy": 0,
    "programming language": 0,
    "quality management": 0,
    "risk": 1,
    "robotics": 0,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 1,
    "sustainability": 1,
    "training": 0,
    "transportation": 0,
    "virtual reality": 2,
    "wearables": 2,
    "web services": 0,
    "": ""
  },
  {
    "term": "control",
    "accessibility": 13,
    "acoustics": 2,
    "aerospace": 4,
    "artificial intelligence": 5,
    "assembly": 4,
    "augmented reality": 92,
    "automation": 6,
    "automobiles": 3,
    "color": 1,
    "computer vision": 6,
    "computing": 5,
    "construction": 1,
    "control": 0,
    "controllers": 1,
    "data modeling": 2,
    "display technology": 13,
    "education": 2,
    "emergency management": 1,
    "energy management": 0,
    "entertainment": 4,
    "food and agriculture": 2,
    "handheld computing": 2,
    "hardware": 3,
    "holography": 1,
    "human computer interaction": 38,
    "human factors": 20,
    "human resources": 2,
    "image processing": 8,
    "information systems": 2,
    "infrastructure": 2,
    "lighting": 1,
    "location based services": 3,
    "machinery": 8,
    "magnetics": 0,
    "maintenance": 3,
    "manufacturing": 13,
    "marketing": 3,
    "materials": 7,
    "mathematics": 6,
    "medical applications": 22,
    "military": 1,
    "mixed reality": 6,
    "mobile computing": 20,
    "operating system": 1,
    "optics": 4,
    "physics": 4,
    "policy": 0,
    "programming language": 3,
    "quality management": 5,
    "risk": 0,
    "robotics": 37,
    "safety": 1,
    "security": 1,
    "sensors": 5,
    "simulation": 4,
    "sustainability": 0,
    "training": 6,
    "transportation": 1,
    "virtual reality": 10,
    "wearables": 29,
    "web services": 3,
    "": ""
  },
  {
    "term": "controllers",
    "accessibility": 0,
    "acoustics": 2,
    "aerospace": 1,
    "artificial intelligence": 2,
    "assembly": 0,
    "augmented reality": 22,
    "automation": 0,
    "automobiles": 0,
    "color": 0,
    "computer vision": 0,
    "computing": 1,
    "construction": 0,
    "control": 1,
    "controllers": 0,
    "data modeling": 7,
    "display technology": 7,
    "education": 0,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 1,
    "handheld computing": 3,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 9,
    "human factors": 3,
    "human resources": 0,
    "image processing": 2,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 1,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 1,
    "marketing": 0,
    "materials": 2,
    "mathematics": 2,
    "medical applications": 0,
    "military": 0,
    "mixed reality": 1,
    "mobile computing": 7,
    "operating system": 0,
    "optics": 0,
    "physics": 1,
    "policy": 0,
    "programming language": 0,
    "quality management": 2,
    "risk": 0,
    "robotics": 2,
    "safety": 0,
    "security": 1,
    "sensors": 1,
    "simulation": 0,
    "sustainability": 0,
    "training": 0,
    "transportation": 0,
    "virtual reality": 8,
    "wearables": 9,
    "web services": 0,
    "": ""
  },
  {
    "term": "data modeling",
    "accessibility": 2,
    "acoustics": 2,
    "aerospace": 2,
    "artificial intelligence": 16,
    "assembly": 0,
    "augmented reality": 73,
    "automation": 3,
    "automobiles": 0,
    "color": 0,
    "computer vision": 3,
    "computing": 5,
    "construction": 3,
    "control": 2,
    "controllers": 7,
    "data modeling": 0,
    "display technology": 9,
    "education": 5,
    "emergency management": 0,
    "energy management": 2,
    "entertainment": 4,
    "food and agriculture": 1,
    "handheld computing": 1,
    "hardware": 1,
    "holography": 1,
    "human computer interaction": 42,
    "human factors": 12,
    "human resources": 0,
    "image processing": 6,
    "information systems": 3,
    "infrastructure": 2,
    "lighting": 0,
    "location based services": 2,
    "machinery": 1,
    "magnetics": 0,
    "maintenance": 1,
    "manufacturing": 8,
    "marketing": 2,
    "materials": 4,
    "mathematics": 2,
    "medical applications": 12,
    "military": 1,
    "mixed reality": 3,
    "mobile computing": 13,
    "operating system": 0,
    "optics": 1,
    "physics": 3,
    "policy": 1,
    "programming language": 2,
    "quality management": 7,
    "risk": 1,
    "robotics": 3,
    "safety": 0,
    "security": 2,
    "sensors": 4,
    "simulation": 2,
    "sustainability": 2,
    "training": 2,
    "transportation": 1,
    "virtual reality": 14,
    "wearables": 13,
    "web services": 1,
    "": ""
  },
  {
    "term": "display technology",
    "accessibility": 8,
    "acoustics": 8,
    "aerospace": 6,
    "artificial intelligence": 22,
    "assembly": 1,
    "augmented reality": 217,
    "automation": 15,
    "automobiles": 8,
    "color": 3,
    "computer vision": 28,
    "computing": 8,
    "construction": 1,
    "control": 13,
    "controllers": 7,
    "data modeling": 9,
    "display technology": 0,
    "education": 3,
    "emergency management": 1,
    "energy management": 2,
    "entertainment": 18,
    "food and agriculture": 2,
    "handheld computing": 15,
    "hardware": 5,
    "holography": 12,
    "human computer interaction": 115,
    "human factors": 52,
    "human resources": 0,
    "image processing": 56,
    "information systems": 1,
    "infrastructure": 11,
    "lighting": 7,
    "location based services": 9,
    "machinery": 16,
    "magnetics": 2,
    "maintenance": 1,
    "manufacturing": 19,
    "marketing": 1,
    "materials": 22,
    "mathematics": 20,
    "medical applications": 31,
    "military": 1,
    "mixed reality": 9,
    "mobile computing": 40,
    "operating system": 1,
    "optics": 26,
    "physics": 9,
    "policy": 0,
    "programming language": 1,
    "quality management": 8,
    "risk": 0,
    "robotics": 18,
    "safety": 2,
    "security": 0,
    "sensors": 8,
    "simulation": 6,
    "sustainability": 6,
    "training": 1,
    "transportation": 12,
    "virtual reality": 41,
    "wearables": 65,
    "web services": 4,
    "": ""
  },
  {
    "term": "education",
    "accessibility": 2,
    "acoustics": 3,
    "aerospace": 1,
    "artificial intelligence": 12,
    "assembly": 0,
    "augmented reality": 75,
    "automation": 2,
    "automobiles": 0,
    "color": 0,
    "computer vision": 3,
    "computing": 6,
    "construction": 1,
    "control": 2,
    "controllers": 0,
    "data modeling": 5,
    "display technology": 3,
    "education": 0,
    "emergency management": 1,
    "energy management": 0,
    "entertainment": 5,
    "food and agriculture": 0,
    "handheld computing": 1,
    "hardware": 1,
    "holography": 0,
    "human computer interaction": 51,
    "human factors": 14,
    "human resources": 1,
    "image processing": 7,
    "information systems": 3,
    "infrastructure": 6,
    "lighting": 0,
    "location based services": 1,
    "machinery": 0,
    "magnetics": 1,
    "maintenance": 2,
    "manufacturing": 5,
    "marketing": 2,
    "materials": 1,
    "mathematics": 4,
    "medical applications": 26,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 13,
    "operating system": 1,
    "optics": 0,
    "physics": 5,
    "policy": 0,
    "programming language": 3,
    "quality management": 0,
    "risk": 1,
    "robotics": 4,
    "safety": 1,
    "security": 1,
    "sensors": 2,
    "simulation": 6,
    "sustainability": 2,
    "training": 18,
    "transportation": 2,
    "virtual reality": 14,
    "wearables": 13,
    "web services": 2,
    "": ""
  },
  {
    "term": "emergency management",
    "accessibility": 0,
    "acoustics": 0,
    "aerospace": 0,
    "artificial intelligence": 0,
    "assembly": 0,
    "augmented reality": 5,
    "automation": 0,
    "automobiles": 0,
    "color": 0,
    "computer vision": 0,
    "computing": 1,
    "construction": 0,
    "control": 1,
    "controllers": 0,
    "data modeling": 0,
    "display technology": 1,
    "education": 1,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 0,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 2,
    "human factors": 0,
    "human resources": 0,
    "image processing": 0,
    "information systems": 0,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 0,
    "machinery": 1,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 0,
    "marketing": 0,
    "materials": 1,
    "mathematics": 1,
    "medical applications": 0,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 1,
    "operating system": 0,
    "optics": 0,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 0,
    "risk": 0,
    "robotics": 1,
    "safety": 2,
    "security": 0,
    "sensors": 0,
    "simulation": 0,
    "sustainability": 0,
    "training": 2,
    "transportation": 1,
    "virtual reality": 0,
    "wearables": 0,
    "web services": 1,
    "": ""
  },
  {
    "term": "energy management",
    "accessibility": 2,
    "acoustics": 0,
    "aerospace": 0,
    "artificial intelligence": 0,
    "assembly": 0,
    "augmented reality": 13,
    "automation": 1,
    "automobiles": 0,
    "color": 0,
    "computer vision": 0,
    "computing": 0,
    "construction": 1,
    "control": 0,
    "controllers": 0,
    "data modeling": 2,
    "display technology": 2,
    "education": 0,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 0,
    "hardware": 3,
    "holography": 0,
    "human computer interaction": 5,
    "human factors": 0,
    "human resources": 0,
    "image processing": 0,
    "information systems": 0,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 1,
    "machinery": 0,
    "magnetics": 1,
    "maintenance": 0,
    "manufacturing": 1,
    "marketing": 0,
    "materials": 2,
    "mathematics": 0,
    "medical applications": 0,
    "military": 1,
    "mixed reality": 0,
    "mobile computing": 2,
    "operating system": 0,
    "optics": 1,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 1,
    "risk": 0,
    "robotics": 1,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 2,
    "sustainability": 3,
    "training": 1,
    "transportation": 0,
    "virtual reality": 1,
    "wearables": 3,
    "web services": 0,
    "": ""
  },
  {
    "term": "entertainment",
    "accessibility": 10,
    "acoustics": 5,
    "aerospace": 3,
    "artificial intelligence": 9,
    "assembly": 1,
    "augmented reality": 105,
    "automation": 3,
    "automobiles": 0,
    "color": 0,
    "computer vision": 5,
    "computing": 10,
    "construction": 1,
    "control": 4,
    "controllers": 0,
    "data modeling": 4,
    "display technology": 18,
    "education": 5,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 9,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 59,
    "human factors": 23,
    "human resources": 0,
    "image processing": 6,
    "information systems": 0,
    "infrastructure": 5,
    "lighting": 0,
    "location based services": 2,
    "machinery": 2,
    "magnetics": 0,
    "maintenance": 1,
    "manufacturing": 6,
    "marketing": 2,
    "materials": 4,
    "mathematics": 3,
    "medical applications": 22,
    "military": 0,
    "mixed reality": 3,
    "mobile computing": 32,
    "operating system": 0,
    "optics": 1,
    "physics": 4,
    "policy": 0,
    "programming language": 1,
    "quality management": 4,
    "risk": 0,
    "robotics": 6,
    "safety": 1,
    "security": 0,
    "sensors": 4,
    "simulation": 2,
    "sustainability": 1,
    "training": 2,
    "transportation": 2,
    "virtual reality": 20,
    "wearables": 23,
    "web services": 2,
    "": ""
  },
  {
    "term": "food and agriculture",
    "accessibility": 0,
    "acoustics": 1,
    "aerospace": 1,
    "artificial intelligence": 3,
    "assembly": 1,
    "augmented reality": 20,
    "automation": 0,
    "automobiles": 0,
    "color": 0,
    "computer vision": 3,
    "computing": 0,
    "construction": 0,
    "control": 2,
    "controllers": 1,
    "data modeling": 1,
    "display technology": 2,
    "education": 0,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 1,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 10,
    "human factors": 5,
    "human resources": 1,
    "image processing": 2,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 1,
    "machinery": 2,
    "magnetics": 0,
    "maintenance": 1,
    "manufacturing": 1,
    "marketing": 2,
    "materials": 0,
    "mathematics": 0,
    "medical applications": 3,
    "military": 0,
    "mixed reality": 3,
    "mobile computing": 0,
    "operating system": 0,
    "optics": 0,
    "physics": 2,
    "policy": 0,
    "programming language": 0,
    "quality management": 2,
    "risk": 0,
    "robotics": 4,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 2,
    "sustainability": 1,
    "training": 2,
    "transportation": 0,
    "virtual reality": 6,
    "wearables": 1,
    "web services": 1,
    "": ""
  },
  {
    "term": "handheld computing",
    "accessibility": 3,
    "acoustics": 3,
    "aerospace": 1,
    "artificial intelligence": 8,
    "assembly": 0,
    "augmented reality": 63,
    "automation": 1,
    "automobiles": 0,
    "color": 2,
    "computer vision": 4,
    "computing": 1,
    "construction": 2,
    "control": 2,
    "controllers": 3,
    "data modeling": 1,
    "display technology": 15,
    "education": 1,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 9,
    "food and agriculture": 1,
    "handheld computing": 0,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 33,
    "human factors": 7,
    "human resources": 0,
    "image processing": 6,
    "information systems": 1,
    "infrastructure": 2,
    "lighting": 0,
    "location based services": 6,
    "machinery": 1,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 4,
    "marketing": 3,
    "materials": 3,
    "mathematics": 4,
    "medical applications": 8,
    "military": 0,
    "mixed reality": 2,
    "mobile computing": 28,
    "operating system": 2,
    "optics": 1,
    "physics": 0,
    "policy": 1,
    "programming language": 1,
    "quality management": 1,
    "risk": 0,
    "robotics": 2,
    "safety": 1,
    "security": 4,
    "sensors": 0,
    "simulation": 1,
    "sustainability": 1,
    "training": 0,
    "transportation": 1,
    "virtual reality": 8,
    "wearables": 6,
    "web services": 4,
    "": ""
  },
  {
    "term": "hardware",
    "accessibility": 3,
    "acoustics": 0,
    "aerospace": 0,
    "artificial intelligence": 0,
    "assembly": 1,
    "augmented reality": 15,
    "automation": 1,
    "automobiles": 0,
    "color": 0,
    "computer vision": 0,
    "computing": 0,
    "construction": 0,
    "control": 3,
    "controllers": 0,
    "data modeling": 1,
    "display technology": 5,
    "education": 1,
    "emergency management": 0,
    "energy management": 3,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 0,
    "hardware": 0,
    "holography": 2,
    "human computer interaction": 6,
    "human factors": 2,
    "human resources": 0,
    "image processing": 3,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 2,
    "location based services": 1,
    "machinery": 2,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 2,
    "marketing": 0,
    "materials": 4,
    "mathematics": 0,
    "medical applications": 4,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 2,
    "operating system": 0,
    "optics": 3,
    "physics": 2,
    "policy": 0,
    "programming language": 0,
    "quality management": 1,
    "risk": 0,
    "robotics": 0,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 0,
    "sustainability": 1,
    "training": 1,
    "transportation": 0,
    "virtual reality": 1,
    "wearables": 9,
    "web services": 0,
    "": ""
  },
  {
    "term": "holography",
    "accessibility": 0,
    "acoustics": 1,
    "aerospace": 0,
    "artificial intelligence": 2,
    "assembly": 0,
    "augmented reality": 29,
    "automation": 0,
    "automobiles": 0,
    "color": 0,
    "computer vision": 1,
    "computing": 0,
    "construction": 0,
    "control": 1,
    "controllers": 0,
    "data modeling": 1,
    "display technology": 12,
    "education": 0,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 0,
    "hardware": 2,
    "holography": 0,
    "human computer interaction": 12,
    "human factors": 3,
    "human resources": 0,
    "image processing": 4,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 4,
    "location based services": 0,
    "machinery": 3,
    "magnetics": 0,
    "maintenance": 1,
    "manufacturing": 3,
    "marketing": 0,
    "materials": 7,
    "mathematics": 1,
    "medical applications": 6,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 2,
    "operating system": 0,
    "optics": 12,
    "physics": 3,
    "policy": 0,
    "programming language": 0,
    "quality management": 0,
    "risk": 0,
    "robotics": 0,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 1,
    "sustainability": 0,
    "training": 0,
    "transportation": 0,
    "virtual reality": 2,
    "wearables": 13,
    "web services": 2,
    "": ""
  },
  {
    "term": "human computer interaction",
    "accessibility": 38,
    "acoustics": 26,
    "aerospace": 14,
    "artificial intelligence": 98,
    "assembly": 7,
    "augmented reality": 654,
    "automation": 20,
    "automobiles": 8,
    "color": 5,
    "computer vision": 39,
    "computing": 47,
    "construction": 11,
    "control": 38,
    "controllers": 9,
    "data modeling": 42,
    "display technology": 115,
    "education": 51,
    "emergency management": 2,
    "energy management": 5,
    "entertainment": 59,
    "food and agriculture": 10,
    "handheld computing": 33,
    "hardware": 6,
    "holography": 12,
    "human computer interaction": 0,
    "human factors": 147,
    "human resources": 4,
    "image processing": 64,
    "information systems": 13,
    "infrastructure": 25,
    "lighting": 3,
    "location based services": 23,
    "machinery": 22,
    "magnetics": 3,
    "maintenance": 11,
    "manufacturing": 56,
    "marketing": 16,
    "materials": 33,
    "mathematics": 35,
    "medical applications": 130,
    "military": 4,
    "mixed reality": 13,
    "mobile computing": 96,
    "operating system": 2,
    "optics": 18,
    "physics": 23,
    "policy": 3,
    "programming language": 10,
    "quality management": 14,
    "risk": 2,
    "robotics": 52,
    "safety": 10,
    "security": 9,
    "sensors": 24,
    "simulation": 18,
    "sustainability": 22,
    "training": 27,
    "transportation": 13,
    "virtual reality": 134,
    "wearables": 137,
    "web services": 20,
    "": ""
  },
  {
    "term": "human factors",
    "accessibility": 29,
    "acoustics": 10,
    "aerospace": 4,
    "artificial intelligence": 32,
    "assembly": 1,
    "augmented reality": 297,
    "automation": 17,
    "automobiles": 7,
    "color": 4,
    "computer vision": 10,
    "computing": 17,
    "construction": 2,
    "control": 20,
    "controllers": 3,
    "data modeling": 12,
    "display technology": 52,
    "education": 14,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 23,
    "food and agriculture": 5,
    "handheld computing": 7,
    "hardware": 2,
    "holography": 3,
    "human computer interaction": 147,
    "human factors": 0,
    "human resources": 2,
    "image processing": 28,
    "information systems": 1,
    "infrastructure": 10,
    "lighting": 2,
    "location based services": 14,
    "machinery": 14,
    "magnetics": 2,
    "maintenance": 6,
    "manufacturing": 16,
    "marketing": 5,
    "materials": 29,
    "mathematics": 4,
    "medical applications": 75,
    "military": 0,
    "mixed reality": 8,
    "mobile computing": 29,
    "operating system": 1,
    "optics": 15,
    "physics": 7,
    "policy": 2,
    "programming language": 3,
    "quality management": 7,
    "risk": 0,
    "robotics": 21,
    "safety": 3,
    "security": 3,
    "sensors": 11,
    "simulation": 14,
    "sustainability": 8,
    "training": 6,
    "transportation": 8,
    "virtual reality": 65,
    "wearables": 76,
    "web services": 5,
    "": ""
  },
  {
    "term": "human resources",
    "accessibility": 0,
    "acoustics": 0,
    "aerospace": 0,
    "artificial intelligence": 2,
    "assembly": 1,
    "augmented reality": 11,
    "automation": 0,
    "automobiles": 1,
    "color": 0,
    "computer vision": 2,
    "computing": 2,
    "construction": 0,
    "control": 2,
    "controllers": 0,
    "data modeling": 0,
    "display technology": 0,
    "education": 1,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 1,
    "handheld computing": 0,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 4,
    "human factors": 2,
    "human resources": 0,
    "image processing": 1,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 1,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 3,
    "manufacturing": 3,
    "marketing": 1,
    "materials": 0,
    "mathematics": 0,
    "medical applications": 1,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 2,
    "operating system": 0,
    "optics": 0,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 3,
    "risk": 0,
    "robotics": 0,
    "safety": 0,
    "security": 0,
    "sensors": 1,
    "simulation": 1,
    "sustainability": 0,
    "training": 4,
    "transportation": 1,
    "virtual reality": 0,
    "wearables": 1,
    "web services": 0,
    "": ""
  },
  {
    "term": "image processing",
    "accessibility": 2,
    "acoustics": 3,
    "aerospace": 5,
    "artificial intelligence": 32,
    "assembly": 3,
    "augmented reality": 133,
    "automation": 6,
    "automobiles": 0,
    "color": 0,
    "computer vision": 36,
    "computing": 10,
    "construction": 2,
    "control": 8,
    "controllers": 2,
    "data modeling": 6,
    "display technology": 56,
    "education": 7,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 6,
    "food and agriculture": 2,
    "handheld computing": 6,
    "hardware": 3,
    "holography": 4,
    "human computer interaction": 64,
    "human factors": 28,
    "human resources": 1,
    "image processing": 0,
    "information systems": 1,
    "infrastructure": 4,
    "lighting": 1,
    "location based services": 4,
    "machinery": 4,
    "magnetics": 2,
    "maintenance": 1,
    "manufacturing": 17,
    "marketing": 1,
    "materials": 5,
    "mathematics": 24,
    "medical applications": 35,
    "military": 0,
    "mixed reality": 2,
    "mobile computing": 15,
    "operating system": 0,
    "optics": 12,
    "physics": 4,
    "policy": 0,
    "programming language": 2,
    "quality management": 2,
    "risk": 0,
    "robotics": 12,
    "safety": 2,
    "security": 2,
    "sensors": 9,
    "simulation": 6,
    "sustainability": 1,
    "training": 5,
    "transportation": 2,
    "virtual reality": 29,
    "wearables": 30,
    "web services": 3,
    "": ""
  },
  {
    "term": "information systems",
    "accessibility": 1,
    "acoustics": 0,
    "aerospace": 2,
    "artificial intelligence": 3,
    "assembly": 1,
    "augmented reality": 22,
    "automation": 2,
    "automobiles": 1,
    "color": 0,
    "computer vision": 0,
    "computing": 0,
    "construction": 1,
    "control": 2,
    "controllers": 0,
    "data modeling": 3,
    "display technology": 1,
    "education": 3,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 1,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 13,
    "human factors": 1,
    "human resources": 0,
    "image processing": 1,
    "information systems": 0,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 2,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 2,
    "manufacturing": 3,
    "marketing": 0,
    "materials": 1,
    "mathematics": 0,
    "medical applications": 3,
    "military": 0,
    "mixed reality": 1,
    "mobile computing": 10,
    "operating system": 0,
    "optics": 0,
    "physics": 2,
    "policy": 0,
    "programming language": 0,
    "quality management": 2,
    "risk": 0,
    "robotics": 0,
    "safety": 0,
    "security": 1,
    "sensors": 1,
    "simulation": 1,
    "sustainability": 2,
    "training": 1,
    "transportation": 2,
    "virtual reality": 8,
    "wearables": 5,
    "web services": 2,
    "": ""
  },
  {
    "term": "infrastructure",
    "accessibility": 2,
    "acoustics": 1,
    "aerospace": 1,
    "artificial intelligence": 9,
    "assembly": 0,
    "augmented reality": 46,
    "automation": 12,
    "automobiles": 3,
    "color": 0,
    "computer vision": 2,
    "computing": 1,
    "construction": 2,
    "control": 2,
    "controllers": 0,
    "data modeling": 2,
    "display technology": 11,
    "education": 6,
    "emergency management": 1,
    "energy management": 1,
    "entertainment": 5,
    "food and agriculture": 0,
    "handheld computing": 2,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 25,
    "human factors": 10,
    "human resources": 0,
    "image processing": 4,
    "information systems": 1,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 1,
    "machinery": 1,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 1,
    "marketing": 5,
    "materials": 0,
    "mathematics": 0,
    "medical applications": 1,
    "military": 0,
    "mixed reality": 1,
    "mobile computing": 8,
    "operating system": 0,
    "optics": 0,
    "physics": 1,
    "policy": 2,
    "programming language": 1,
    "quality management": 1,
    "risk": 0,
    "robotics": 2,
    "safety": 0,
    "security": 0,
    "sensors": 3,
    "simulation": 2,
    "sustainability": 1,
    "training": 1,
    "transportation": 11,
    "virtual reality": 3,
    "wearables": 6,
    "web services": 1,
    "": ""
  },
  {
    "term": "lighting",
    "accessibility": 0,
    "acoustics": 0,
    "aerospace": 0,
    "artificial intelligence": 0,
    "assembly": 0,
    "augmented reality": 10,
    "automation": 0,
    "automobiles": 0,
    "color": 2,
    "computer vision": 1,
    "computing": 0,
    "construction": 0,
    "control": 1,
    "controllers": 0,
    "data modeling": 0,
    "display technology": 7,
    "education": 0,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 0,
    "hardware": 2,
    "holography": 4,
    "human computer interaction": 3,
    "human factors": 2,
    "human resources": 0,
    "image processing": 1,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 0,
    "machinery": 3,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 1,
    "marketing": 0,
    "materials": 4,
    "mathematics": 0,
    "medical applications": 3,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 1,
    "operating system": 0,
    "optics": 6,
    "physics": 2,
    "policy": 0,
    "programming language": 0,
    "quality management": 0,
    "risk": 0,
    "robotics": 0,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 0,
    "sustainability": 0,
    "training": 0,
    "transportation": 0,
    "virtual reality": 1,
    "wearables": 7,
    "web services": 0,
    "": ""
  },
  {
    "term": "location based services",
    "accessibility": 5,
    "acoustics": 4,
    "aerospace": 3,
    "artificial intelligence": 7,
    "assembly": 0,
    "augmented reality": 56,
    "automation": 0,
    "automobiles": 1,
    "color": 0,
    "computer vision": 3,
    "computing": 3,
    "construction": 0,
    "control": 3,
    "controllers": 1,
    "data modeling": 2,
    "display technology": 9,
    "education": 1,
    "emergency management": 0,
    "energy management": 1,
    "entertainment": 2,
    "food and agriculture": 1,
    "handheld computing": 6,
    "hardware": 1,
    "holography": 0,
    "human computer interaction": 23,
    "human factors": 14,
    "human resources": 1,
    "image processing": 4,
    "information systems": 2,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 0,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 1,
    "marketing": 1,
    "materials": 6,
    "mathematics": 3,
    "medical applications": 9,
    "military": 1,
    "mixed reality": 1,
    "mobile computing": 12,
    "operating system": 1,
    "optics": 1,
    "physics": 4,
    "policy": 0,
    "programming language": 1,
    "quality management": 3,
    "risk": 0,
    "robotics": 8,
    "safety": 1,
    "security": 0,
    "sensors": 3,
    "simulation": 0,
    "sustainability": 1,
    "training": 1,
    "transportation": 1,
    "virtual reality": 12,
    "wearables": 15,
    "web services": 4,
    "": ""
  },
  {
    "term": "machinery",
    "accessibility": 0,
    "acoustics": 2,
    "aerospace": 1,
    "artificial intelligence": 3,
    "assembly": 0,
    "augmented reality": 44,
    "automation": 3,
    "automobiles": 1,
    "color": 0,
    "computer vision": 5,
    "computing": 4,
    "construction": 0,
    "control": 8,
    "controllers": 0,
    "data modeling": 1,
    "display technology": 16,
    "education": 0,
    "emergency management": 1,
    "energy management": 0,
    "entertainment": 2,
    "food and agriculture": 2,
    "handheld computing": 1,
    "hardware": 2,
    "holography": 3,
    "human computer interaction": 22,
    "human factors": 14,
    "human resources": 0,
    "image processing": 4,
    "information systems": 0,
    "infrastructure": 1,
    "lighting": 3,
    "location based services": 0,
    "machinery": 0,
    "magnetics": 3,
    "maintenance": 3,
    "manufacturing": 6,
    "marketing": 0,
    "materials": 8,
    "mathematics": 6,
    "medical applications": 8,
    "military": 0,
    "mixed reality": 6,
    "mobile computing": 10,
    "operating system": 0,
    "optics": 6,
    "physics": 7,
    "policy": 0,
    "programming language": 1,
    "quality management": 0,
    "risk": 0,
    "robotics": 14,
    "safety": 2,
    "security": 0,
    "sensors": 5,
    "simulation": 3,
    "sustainability": 3,
    "training": 1,
    "transportation": 0,
    "virtual reality": 7,
    "wearables": 9,
    "web services": 1,
    "": ""
  },
  {
    "term": "magnetics",
    "accessibility": 0,
    "acoustics": 1,
    "aerospace": 0,
    "artificial intelligence": 1,
    "assembly": 0,
    "augmented reality": 8,
    "automation": 2,
    "automobiles": 0,
    "color": 0,
    "computer vision": 1,
    "computing": 0,
    "construction": 0,
    "control": 0,
    "controllers": 0,
    "data modeling": 0,
    "display technology": 2,
    "education": 1,
    "emergency management": 0,
    "energy management": 1,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 0,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 3,
    "human factors": 2,
    "human resources": 0,
    "image processing": 2,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 0,
    "machinery": 3,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 2,
    "marketing": 0,
    "materials": 1,
    "mathematics": 2,
    "medical applications": 3,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 0,
    "operating system": 0,
    "optics": 0,
    "physics": 3,
    "policy": 0,
    "programming language": 0,
    "quality management": 0,
    "risk": 0,
    "robotics": 0,
    "safety": 0,
    "security": 0,
    "sensors": 1,
    "simulation": 0,
    "sustainability": 0,
    "training": 0,
    "transportation": 0,
    "virtual reality": 5,
    "wearables": 2,
    "web services": 0,
    "": ""
  },
  {
    "term": "maintenance",
    "accessibility": 0,
    "acoustics": 0,
    "aerospace": 3,
    "artificial intelligence": 3,
    "assembly": 2,
    "augmented reality": 24,
    "automation": 1,
    "automobiles": 0,
    "color": 0,
    "computer vision": 3,
    "computing": 2,
    "construction": 0,
    "control": 3,
    "controllers": 0,
    "data modeling": 1,
    "display technology": 1,
    "education": 2,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 1,
    "food and agriculture": 1,
    "handheld computing": 0,
    "hardware": 0,
    "holography": 1,
    "human computer interaction": 11,
    "human factors": 6,
    "human resources": 3,
    "image processing": 1,
    "information systems": 2,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 0,
    "machinery": 3,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 12,
    "marketing": 0,
    "materials": 0,
    "mathematics": 0,
    "medical applications": 1,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 3,
    "operating system": 0,
    "optics": 1,
    "physics": 1,
    "policy": 0,
    "programming language": 1,
    "quality management": 2,
    "risk": 0,
    "robotics": 3,
    "safety": 0,
    "security": 0,
    "sensors": 1,
    "simulation": 2,
    "sustainability": 1,
    "training": 1,
    "transportation": 0,
    "virtual reality": 4,
    "wearables": 6,
    "web services": 0,
    "": ""
  },
  {
    "term": "manufacturing",
    "accessibility": 1,
    "acoustics": 1,
    "aerospace": 6,
    "artificial intelligence": 20,
    "assembly": 17,
    "augmented reality": 125,
    "automation": 5,
    "automobiles": 4,
    "color": 0,
    "computer vision": 9,
    "computing": 8,
    "construction": 4,
    "control": 13,
    "controllers": 1,
    "data modeling": 8,
    "display technology": 19,
    "education": 5,
    "emergency management": 0,
    "energy management": 1,
    "entertainment": 6,
    "food and agriculture": 1,
    "handheld computing": 4,
    "hardware": 2,
    "holography": 3,
    "human computer interaction": 56,
    "human factors": 16,
    "human resources": 3,
    "image processing": 17,
    "information systems": 3,
    "infrastructure": 1,
    "lighting": 1,
    "location based services": 1,
    "machinery": 6,
    "magnetics": 2,
    "maintenance": 12,
    "manufacturing": 0,
    "marketing": 2,
    "materials": 4,
    "mathematics": 9,
    "medical applications": 18,
    "military": 1,
    "mixed reality": 3,
    "mobile computing": 20,
    "operating system": 1,
    "optics": 4,
    "physics": 3,
    "policy": 0,
    "programming language": 2,
    "quality management": 11,
    "risk": 0,
    "robotics": 20,
    "safety": 1,
    "security": 0,
    "sensors": 1,
    "simulation": 8,
    "sustainability": 5,
    "training": 7,
    "transportation": 4,
    "virtual reality": 27,
    "wearables": 19,
    "web services": 4,
    "": ""
  },
  {
    "term": "marketing",
    "accessibility": 0,
    "acoustics": 0,
    "aerospace": 3,
    "artificial intelligence": 4,
    "assembly": 0,
    "augmented reality": 27,
    "automation": 1,
    "automobiles": 1,
    "color": 0,
    "computer vision": 2,
    "computing": 0,
    "construction": 1,
    "control": 3,
    "controllers": 0,
    "data modeling": 2,
    "display technology": 1,
    "education": 2,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 2,
    "food and agriculture": 2,
    "handheld computing": 3,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 16,
    "human factors": 5,
    "human resources": 1,
    "image processing": 1,
    "information systems": 0,
    "infrastructure": 5,
    "lighting": 0,
    "location based services": 1,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 2,
    "marketing": 0,
    "materials": 0,
    "mathematics": 0,
    "medical applications": 1,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 4,
    "operating system": 0,
    "optics": 0,
    "physics": 2,
    "policy": 1,
    "programming language": 1,
    "quality management": 2,
    "risk": 0,
    "robotics": 1,
    "safety": 0,
    "security": 0,
    "sensors": 1,
    "simulation": 2,
    "sustainability": 1,
    "training": 2,
    "transportation": 0,
    "virtual reality": 3,
    "wearables": 3,
    "web services": 3,
    "": ""
  },
  {
    "term": "materials",
    "accessibility": 2,
    "acoustics": 2,
    "aerospace": 2,
    "artificial intelligence": 7,
    "assembly": 0,
    "augmented reality": 84,
    "automation": 3,
    "automobiles": 1,
    "color": 2,
    "computer vision": 2,
    "computing": 2,
    "construction": 1,
    "control": 7,
    "controllers": 2,
    "data modeling": 4,
    "display technology": 22,
    "education": 1,
    "emergency management": 1,
    "energy management": 2,
    "entertainment": 4,
    "food and agriculture": 0,
    "handheld computing": 3,
    "hardware": 4,
    "holography": 7,
    "human computer interaction": 33,
    "human factors": 29,
    "human resources": 0,
    "image processing": 5,
    "information systems": 1,
    "infrastructure": 0,
    "lighting": 4,
    "location based services": 6,
    "machinery": 8,
    "magnetics": 1,
    "maintenance": 0,
    "manufacturing": 4,
    "marketing": 0,
    "materials": 0,
    "mathematics": 1,
    "medical applications": 12,
    "military": 0,
    "mixed reality": 5,
    "mobile computing": 5,
    "operating system": 0,
    "optics": 15,
    "physics": 5,
    "policy": 0,
    "programming language": 2,
    "quality management": 8,
    "risk": 0,
    "robotics": 3,
    "safety": 2,
    "security": 0,
    "sensors": 7,
    "simulation": 1,
    "sustainability": 5,
    "training": 1,
    "transportation": 0,
    "virtual reality": 18,
    "wearables": 25,
    "web services": 0,
    "": ""
  },
  {
    "term": "mathematics",
    "accessibility": 1,
    "acoustics": 5,
    "aerospace": 3,
    "artificial intelligence": 33,
    "assembly": 1,
    "augmented reality": 65,
    "automation": 1,
    "automobiles": 0,
    "color": 0,
    "computer vision": 19,
    "computing": 3,
    "construction": 2,
    "control": 6,
    "controllers": 2,
    "data modeling": 2,
    "display technology": 20,
    "education": 4,
    "emergency management": 1,
    "energy management": 0,
    "entertainment": 3,
    "food and agriculture": 0,
    "handheld computing": 4,
    "hardware": 0,
    "holography": 1,
    "human computer interaction": 35,
    "human factors": 4,
    "human resources": 0,
    "image processing": 24,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 3,
    "machinery": 6,
    "magnetics": 2,
    "maintenance": 0,
    "manufacturing": 9,
    "marketing": 0,
    "materials": 1,
    "mathematics": 0,
    "medical applications": 15,
    "military": 1,
    "mixed reality": 1,
    "mobile computing": 13,
    "operating system": 0,
    "optics": 4,
    "physics": 3,
    "policy": 0,
    "programming language": 0,
    "quality management": 3,
    "risk": 0,
    "robotics": 7,
    "safety": 0,
    "security": 1,
    "sensors": 4,
    "simulation": 2,
    "sustainability": 2,
    "training": 3,
    "transportation": 1,
    "virtual reality": 15,
    "wearables": 14,
    "web services": 1,
    "": ""
  },
  {
    "term": "medical applications",
    "accessibility": 61,
    "acoustics": 6,
    "aerospace": 5,
    "artificial intelligence": 42,
    "assembly": 0,
    "augmented reality": 279,
    "automation": 4,
    "automobiles": 1,
    "color": 0,
    "computer vision": 10,
    "computing": 9,
    "construction": 1,
    "control": 22,
    "controllers": 0,
    "data modeling": 12,
    "display technology": 31,
    "education": 26,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 22,
    "food and agriculture": 3,
    "handheld computing": 8,
    "hardware": 4,
    "holography": 6,
    "human computer interaction": 130,
    "human factors": 75,
    "human resources": 1,
    "image processing": 35,
    "information systems": 3,
    "infrastructure": 1,
    "lighting": 3,
    "location based services": 9,
    "machinery": 8,
    "magnetics": 3,
    "maintenance": 1,
    "manufacturing": 18,
    "marketing": 1,
    "materials": 12,
    "mathematics": 15,
    "medical applications": 0,
    "military": 0,
    "mixed reality": 5,
    "mobile computing": 26,
    "operating system": 2,
    "optics": 9,
    "physics": 10,
    "policy": 1,
    "programming language": 0,
    "quality management": 9,
    "risk": 1,
    "robotics": 13,
    "safety": 8,
    "security": 3,
    "sensors": 12,
    "simulation": 22,
    "sustainability": 8,
    "training": 20,
    "transportation": 1,
    "virtual reality": 66,
    "wearables": 53,
    "web services": 4,
    "": ""
  },
  {
    "term": "military",
    "accessibility": 0,
    "acoustics": 1,
    "aerospace": 0,
    "artificial intelligence": 1,
    "assembly": 0,
    "augmented reality": 9,
    "automation": 2,
    "automobiles": 0,
    "color": 0,
    "computer vision": 0,
    "computing": 0,
    "construction": 0,
    "control": 1,
    "controllers": 0,
    "data modeling": 1,
    "display technology": 1,
    "education": 0,
    "emergency management": 0,
    "energy management": 1,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 0,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 4,
    "human factors": 0,
    "human resources": 0,
    "image processing": 0,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 1,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 1,
    "marketing": 0,
    "materials": 0,
    "mathematics": 1,
    "medical applications": 0,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 0,
    "operating system": 0,
    "optics": 0,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 0,
    "risk": 0,
    "robotics": 1,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 1,
    "sustainability": 0,
    "training": 2,
    "transportation": 0,
    "virtual reality": 2,
    "wearables": 1,
    "web services": 1,
    "": ""
  },
  {
    "term": "mixed reality",
    "accessibility": 0,
    "acoustics": 1,
    "aerospace": 2,
    "artificial intelligence": 3,
    "assembly": 0,
    "augmented reality": 32,
    "automation": 0,
    "automobiles": 2,
    "color": 1,
    "computer vision": 2,
    "computing": 0,
    "construction": 0,
    "control": 6,
    "controllers": 1,
    "data modeling": 3,
    "display technology": 9,
    "education": 0,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 3,
    "food and agriculture": 3,
    "handheld computing": 2,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 13,
    "human factors": 8,
    "human resources": 0,
    "image processing": 2,
    "information systems": 1,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 1,
    "machinery": 6,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 3,
    "marketing": 0,
    "materials": 5,
    "mathematics": 1,
    "medical applications": 5,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 7,
    "operating system": 0,
    "optics": 0,
    "physics": 2,
    "policy": 0,
    "programming language": 0,
    "quality management": 3,
    "risk": 0,
    "robotics": 8,
    "safety": 0,
    "security": 0,
    "sensors": 3,
    "simulation": 1,
    "sustainability": 1,
    "training": 1,
    "transportation": 0,
    "virtual reality": 6,
    "wearables": 8,
    "web services": 0,
    "": ""
  },
  {
    "term": "mobile computing",
    "accessibility": 13,
    "acoustics": 8,
    "aerospace": 7,
    "artificial intelligence": 22,
    "assembly": 5,
    "augmented reality": 212,
    "automation": 8,
    "automobiles": 0,
    "color": 0,
    "computer vision": 14,
    "computing": 16,
    "construction": 2,
    "control": 20,
    "controllers": 7,
    "data modeling": 13,
    "display technology": 40,
    "education": 13,
    "emergency management": 1,
    "energy management": 2,
    "entertainment": 32,
    "food and agriculture": 0,
    "handheld computing": 28,
    "hardware": 2,
    "holography": 2,
    "human computer interaction": 96,
    "human factors": 29,
    "human resources": 2,
    "image processing": 15,
    "information systems": 10,
    "infrastructure": 8,
    "lighting": 1,
    "location based services": 12,
    "machinery": 10,
    "magnetics": 0,
    "maintenance": 3,
    "manufacturing": 20,
    "marketing": 4,
    "materials": 5,
    "mathematics": 13,
    "medical applications": 26,
    "military": 0,
    "mixed reality": 7,
    "mobile computing": 0,
    "operating system": 5,
    "optics": 6,
    "physics": 8,
    "policy": 1,
    "programming language": 4,
    "quality management": 10,
    "risk": 0,
    "robotics": 29,
    "safety": 0,
    "security": 5,
    "sensors": 6,
    "simulation": 1,
    "sustainability": 5,
    "training": 6,
    "transportation": 11,
    "virtual reality": 18,
    "wearables": 40,
    "web services": 12,
    "": ""
  },
  {
    "term": "operating system",
    "accessibility": 3,
    "acoustics": 0,
    "aerospace": 0,
    "artificial intelligence": 1,
    "assembly": 0,
    "augmented reality": 8,
    "automation": 0,
    "automobiles": 0,
    "color": 0,
    "computer vision": 0,
    "computing": 0,
    "construction": 0,
    "control": 1,
    "controllers": 0,
    "data modeling": 0,
    "display technology": 1,
    "education": 1,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 2,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 2,
    "human factors": 1,
    "human resources": 0,
    "image processing": 0,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 1,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 1,
    "marketing": 0,
    "materials": 0,
    "mathematics": 0,
    "medical applications": 2,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 5,
    "operating system": 0,
    "optics": 1,
    "physics": 0,
    "policy": 0,
    "programming language": 1,
    "quality management": 0,
    "risk": 0,
    "robotics": 1,
    "safety": 0,
    "security": 0,
    "sensors": 2,
    "simulation": 0,
    "sustainability": 0,
    "training": 0,
    "transportation": 0,
    "virtual reality": 0,
    "wearables": 1,
    "web services": 2,
    "": ""
  },
  {
    "term": "optics",
    "accessibility": 3,
    "acoustics": 0,
    "aerospace": 0,
    "artificial intelligence": 3,
    "assembly": 0,
    "augmented reality": 48,
    "automation": 0,
    "automobiles": 2,
    "color": 1,
    "computer vision": 0,
    "computing": 2,
    "construction": 0,
    "control": 4,
    "controllers": 0,
    "data modeling": 1,
    "display technology": 26,
    "education": 0,
    "emergency management": 0,
    "energy management": 1,
    "entertainment": 1,
    "food and agriculture": 0,
    "handheld computing": 1,
    "hardware": 3,
    "holography": 12,
    "human computer interaction": 18,
    "human factors": 15,
    "human resources": 0,
    "image processing": 12,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 6,
    "location based services": 1,
    "machinery": 6,
    "magnetics": 0,
    "maintenance": 1,
    "manufacturing": 4,
    "marketing": 0,
    "materials": 15,
    "mathematics": 4,
    "medical applications": 9,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 6,
    "operating system": 1,
    "optics": 0,
    "physics": 4,
    "policy": 0,
    "programming language": 0,
    "quality management": 1,
    "risk": 0,
    "robotics": 4,
    "safety": 1,
    "security": 0,
    "sensors": 0,
    "simulation": 1,
    "sustainability": 0,
    "training": 0,
    "transportation": 0,
    "virtual reality": 6,
    "wearables": 17,
    "web services": 0,
    "": ""
  },
  {
    "term": "physics",
    "accessibility": 1,
    "acoustics": 5,
    "aerospace": 5,
    "artificial intelligence": 4,
    "assembly": 0,
    "augmented reality": 37,
    "automation": 2,
    "automobiles": 0,
    "color": 0,
    "computer vision": 3,
    "computing": 1,
    "construction": 1,
    "control": 4,
    "controllers": 1,
    "data modeling": 3,
    "display technology": 9,
    "education": 5,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 4,
    "food and agriculture": 2,
    "handheld computing": 0,
    "hardware": 2,
    "holography": 3,
    "human computer interaction": 23,
    "human factors": 7,
    "human resources": 0,
    "image processing": 4,
    "information systems": 2,
    "infrastructure": 1,
    "lighting": 2,
    "location based services": 4,
    "machinery": 7,
    "magnetics": 3,
    "maintenance": 1,
    "manufacturing": 3,
    "marketing": 2,
    "materials": 5,
    "mathematics": 3,
    "medical applications": 10,
    "military": 0,
    "mixed reality": 2,
    "mobile computing": 8,
    "operating system": 0,
    "optics": 4,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 2,
    "risk": 0,
    "robotics": 3,
    "safety": 0,
    "security": 0,
    "sensors": 1,
    "simulation": 1,
    "sustainability": 0,
    "training": 3,
    "transportation": 0,
    "virtual reality": 10,
    "wearables": 6,
    "web services": 2,
    "": ""
  },
  {
    "term": "policy",
    "accessibility": 1,
    "acoustics": 0,
    "aerospace": 0,
    "artificial intelligence": 2,
    "assembly": 0,
    "augmented reality": 3,
    "automation": 0,
    "automobiles": 0,
    "color": 0,
    "computer vision": 0,
    "computing": 0,
    "construction": 0,
    "control": 0,
    "controllers": 0,
    "data modeling": 1,
    "display technology": 0,
    "education": 0,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 1,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 3,
    "human factors": 2,
    "human resources": 0,
    "image processing": 0,
    "information systems": 0,
    "infrastructure": 2,
    "lighting": 0,
    "location based services": 0,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 0,
    "marketing": 1,
    "materials": 0,
    "mathematics": 0,
    "medical applications": 1,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 1,
    "operating system": 0,
    "optics": 0,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 0,
    "risk": 0,
    "robotics": 1,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 1,
    "sustainability": 1,
    "training": 0,
    "transportation": 0,
    "virtual reality": 0,
    "wearables": 1,
    "web services": 0,
    "": ""
  },
  {
    "term": "programming language",
    "accessibility": 1,
    "acoustics": 0,
    "aerospace": 0,
    "artificial intelligence": 2,
    "assembly": 0,
    "augmented reality": 18,
    "automation": 0,
    "automobiles": 0,
    "color": 0,
    "computer vision": 1,
    "computing": 2,
    "construction": 0,
    "control": 3,
    "controllers": 0,
    "data modeling": 2,
    "display technology": 1,
    "education": 3,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 1,
    "food and agriculture": 0,
    "handheld computing": 1,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 10,
    "human factors": 3,
    "human resources": 0,
    "image processing": 2,
    "information systems": 0,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 1,
    "machinery": 1,
    "magnetics": 0,
    "maintenance": 1,
    "manufacturing": 2,
    "marketing": 1,
    "materials": 2,
    "mathematics": 0,
    "medical applications": 0,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 4,
    "operating system": 1,
    "optics": 0,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 1,
    "risk": 0,
    "robotics": 1,
    "safety": 0,
    "security": 1,
    "sensors": 0,
    "simulation": 1,
    "sustainability": 0,
    "training": 3,
    "transportation": 0,
    "virtual reality": 0,
    "wearables": 4,
    "web services": 2,
    "": ""
  },
  {
    "term": "quality management",
    "accessibility": 1,
    "acoustics": 2,
    "aerospace": 4,
    "artificial intelligence": 12,
    "assembly": 2,
    "augmented reality": 49,
    "automation": 4,
    "automobiles": 2,
    "color": 0,
    "computer vision": 2,
    "computing": 3,
    "construction": 0,
    "control": 5,
    "controllers": 2,
    "data modeling": 7,
    "display technology": 8,
    "education": 0,
    "emergency management": 0,
    "energy management": 1,
    "entertainment": 4,
    "food and agriculture": 2,
    "handheld computing": 1,
    "hardware": 1,
    "holography": 0,
    "human computer interaction": 14,
    "human factors": 7,
    "human resources": 3,
    "image processing": 2,
    "information systems": 2,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 3,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 2,
    "manufacturing": 11,
    "marketing": 2,
    "materials": 8,
    "mathematics": 3,
    "medical applications": 9,
    "military": 0,
    "mixed reality": 3,
    "mobile computing": 10,
    "operating system": 0,
    "optics": 1,
    "physics": 2,
    "policy": 0,
    "programming language": 1,
    "quality management": 0,
    "risk": 0,
    "robotics": 3,
    "safety": 1,
    "security": 1,
    "sensors": 2,
    "simulation": 1,
    "sustainability": 2,
    "training": 3,
    "transportation": 1,
    "virtual reality": 9,
    "wearables": 14,
    "web services": 4,
    "": ""
  },
  {
    "term": "risk",
    "accessibility": 0,
    "acoustics": 0,
    "aerospace": 0,
    "artificial intelligence": 0,
    "assembly": 0,
    "augmented reality": 3,
    "automation": 1,
    "automobiles": 0,
    "color": 0,
    "computer vision": 0,
    "computing": 0,
    "construction": 1,
    "control": 0,
    "controllers": 0,
    "data modeling": 1,
    "display technology": 0,
    "education": 1,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 0,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 2,
    "human factors": 0,
    "human resources": 0,
    "image processing": 0,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 0,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 0,
    "marketing": 0,
    "materials": 0,
    "mathematics": 0,
    "medical applications": 1,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 0,
    "operating system": 0,
    "optics": 0,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 0,
    "risk": 0,
    "robotics": 1,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 0,
    "sustainability": 0,
    "training": 0,
    "transportation": 0,
    "virtual reality": 1,
    "wearables": 1,
    "web services": 0,
    "": ""
  },
  {
    "term": "robotics",
    "accessibility": 6,
    "acoustics": 3,
    "aerospace": 6,
    "artificial intelligence": 8,
    "assembly": 3,
    "augmented reality": 111,
    "automation": 5,
    "automobiles": 0,
    "color": 0,
    "computer vision": 10,
    "computing": 5,
    "construction": 0,
    "control": 37,
    "controllers": 2,
    "data modeling": 3,
    "display technology": 18,
    "education": 4,
    "emergency management": 1,
    "energy management": 1,
    "entertainment": 6,
    "food and agriculture": 4,
    "handheld computing": 2,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 52,
    "human factors": 21,
    "human resources": 0,
    "image processing": 12,
    "information systems": 0,
    "infrastructure": 2,
    "lighting": 0,
    "location based services": 8,
    "machinery": 14,
    "magnetics": 0,
    "maintenance": 3,
    "manufacturing": 20,
    "marketing": 1,
    "materials": 3,
    "mathematics": 7,
    "medical applications": 13,
    "military": 1,
    "mixed reality": 8,
    "mobile computing": 29,
    "operating system": 1,
    "optics": 4,
    "physics": 3,
    "policy": 1,
    "programming language": 1,
    "quality management": 3,
    "risk": 1,
    "robotics": 0,
    "safety": 2,
    "security": 0,
    "sensors": 3,
    "simulation": 4,
    "sustainability": 2,
    "training": 3,
    "transportation": 2,
    "virtual reality": 12,
    "wearables": 22,
    "web services": 2,
    "": ""
  },
  {
    "term": "safety",
    "accessibility": 6,
    "acoustics": 0,
    "aerospace": 0,
    "artificial intelligence": 0,
    "assembly": 0,
    "augmented reality": 16,
    "automation": 1,
    "automobiles": 0,
    "color": 1,
    "computer vision": 0,
    "computing": 1,
    "construction": 0,
    "control": 1,
    "controllers": 0,
    "data modeling": 0,
    "display technology": 2,
    "education": 1,
    "emergency management": 2,
    "energy management": 0,
    "entertainment": 1,
    "food and agriculture": 0,
    "handheld computing": 1,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 10,
    "human factors": 3,
    "human resources": 0,
    "image processing": 2,
    "information systems": 0,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 1,
    "machinery": 2,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 1,
    "marketing": 0,
    "materials": 2,
    "mathematics": 0,
    "medical applications": 8,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 0,
    "operating system": 0,
    "optics": 1,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 1,
    "risk": 0,
    "robotics": 2,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 0,
    "sustainability": 1,
    "training": 3,
    "transportation": 0,
    "virtual reality": 5,
    "wearables": 3,
    "web services": 0,
    "": ""
  },
  {
    "term": "security",
    "accessibility": 1,
    "acoustics": 2,
    "aerospace": 0,
    "artificial intelligence": 1,
    "assembly": 0,
    "augmented reality": 23,
    "automation": 0,
    "automobiles": 0,
    "color": 0,
    "computer vision": 1,
    "computing": 1,
    "construction": 0,
    "control": 1,
    "controllers": 1,
    "data modeling": 2,
    "display technology": 0,
    "education": 1,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 0,
    "food and agriculture": 0,
    "handheld computing": 4,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 9,
    "human factors": 3,
    "human resources": 0,
    "image processing": 2,
    "information systems": 1,
    "infrastructure": 0,
    "lighting": 0,
    "location based services": 0,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 0,
    "marketing": 0,
    "materials": 0,
    "mathematics": 1,
    "medical applications": 3,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 5,
    "operating system": 0,
    "optics": 0,
    "physics": 0,
    "policy": 0,
    "programming language": 1,
    "quality management": 1,
    "risk": 0,
    "robotics": 0,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 0,
    "sustainability": 1,
    "training": 0,
    "transportation": 0,
    "virtual reality": 3,
    "wearables": 2,
    "web services": 2,
    "": ""
  },
  {
    "term": "sensors",
    "accessibility": 5,
    "acoustics": 4,
    "aerospace": 0,
    "artificial intelligence": 6,
    "assembly": 0,
    "augmented reality": 37,
    "automation": 1,
    "automobiles": 0,
    "color": 0,
    "computer vision": 8,
    "computing": 0,
    "construction": 0,
    "control": 5,
    "controllers": 1,
    "data modeling": 4,
    "display technology": 8,
    "education": 2,
    "emergency management": 0,
    "energy management": 0,
    "entertainment": 4,
    "food and agriculture": 0,
    "handheld computing": 0,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 24,
    "human factors": 11,
    "human resources": 1,
    "image processing": 9,
    "information systems": 1,
    "infrastructure": 3,
    "lighting": 0,
    "location based services": 3,
    "machinery": 5,
    "magnetics": 1,
    "maintenance": 1,
    "manufacturing": 1,
    "marketing": 1,
    "materials": 7,
    "mathematics": 4,
    "medical applications": 12,
    "military": 0,
    "mixed reality": 3,
    "mobile computing": 6,
    "operating system": 2,
    "optics": 0,
    "physics": 1,
    "policy": 0,
    "programming language": 0,
    "quality management": 2,
    "risk": 0,
    "robotics": 3,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 3,
    "sustainability": 0,
    "training": 2,
    "transportation": 0,
    "virtual reality": 8,
    "wearables": 13,
    "web services": 1,
    "": ""
  },
  {
    "term": "simulation",
    "accessibility": 4,
    "acoustics": 1,
    "aerospace": 0,
    "artificial intelligence": 4,
    "assembly": 1,
    "augmented reality": 40,
    "automation": 3,
    "automobiles": 1,
    "color": 0,
    "computer vision": 1,
    "computing": 0,
    "construction": 1,
    "control": 4,
    "controllers": 0,
    "data modeling": 2,
    "display technology": 6,
    "education": 6,
    "emergency management": 0,
    "energy management": 2,
    "entertainment": 2,
    "food and agriculture": 2,
    "handheld computing": 1,
    "hardware": 0,
    "holography": 1,
    "human computer interaction": 18,
    "human factors": 14,
    "human resources": 1,
    "image processing": 6,
    "information systems": 1,
    "infrastructure": 2,
    "lighting": 0,
    "location based services": 0,
    "machinery": 3,
    "magnetics": 0,
    "maintenance": 2,
    "manufacturing": 8,
    "marketing": 2,
    "materials": 1,
    "mathematics": 2,
    "medical applications": 22,
    "military": 1,
    "mixed reality": 1,
    "mobile computing": 1,
    "operating system": 0,
    "optics": 1,
    "physics": 1,
    "policy": 1,
    "programming language": 1,
    "quality management": 1,
    "risk": 0,
    "robotics": 4,
    "safety": 0,
    "security": 0,
    "sensors": 3,
    "simulation": 0,
    "sustainability": 3,
    "training": 5,
    "transportation": 0,
    "virtual reality": 15,
    "wearables": 4,
    "web services": 0,
    "": ""
  },
  {
    "term": "sustainability",
    "accessibility": 2,
    "acoustics": 1,
    "aerospace": 0,
    "artificial intelligence": 4,
    "assembly": 0,
    "augmented reality": 33,
    "automation": 1,
    "automobiles": 1,
    "color": 0,
    "computer vision": 0,
    "computing": 2,
    "construction": 1,
    "control": 0,
    "controllers": 0,
    "data modeling": 2,
    "display technology": 6,
    "education": 2,
    "emergency management": 0,
    "energy management": 3,
    "entertainment": 1,
    "food and agriculture": 1,
    "handheld computing": 1,
    "hardware": 1,
    "holography": 0,
    "human computer interaction": 22,
    "human factors": 8,
    "human resources": 0,
    "image processing": 1,
    "information systems": 2,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 1,
    "machinery": 3,
    "magnetics": 0,
    "maintenance": 1,
    "manufacturing": 5,
    "marketing": 1,
    "materials": 5,
    "mathematics": 2,
    "medical applications": 8,
    "military": 0,
    "mixed reality": 1,
    "mobile computing": 5,
    "operating system": 0,
    "optics": 0,
    "physics": 0,
    "policy": 1,
    "programming language": 0,
    "quality management": 2,
    "risk": 0,
    "robotics": 2,
    "safety": 1,
    "security": 1,
    "sensors": 0,
    "simulation": 3,
    "sustainability": 0,
    "training": 1,
    "transportation": 0,
    "virtual reality": 11,
    "wearables": 6,
    "web services": 1,
    "": ""
  },
  {
    "term": "training",
    "accessibility": 6,
    "acoustics": 1,
    "aerospace": 3,
    "artificial intelligence": 8,
    "assembly": 6,
    "augmented reality": 49,
    "automation": 1,
    "automobiles": 2,
    "color": 0,
    "computer vision": 1,
    "computing": 5,
    "construction": 0,
    "control": 6,
    "controllers": 0,
    "data modeling": 2,
    "display technology": 1,
    "education": 18,
    "emergency management": 2,
    "energy management": 1,
    "entertainment": 2,
    "food and agriculture": 2,
    "handheld computing": 0,
    "hardware": 1,
    "holography": 0,
    "human computer interaction": 27,
    "human factors": 6,
    "human resources": 4,
    "image processing": 5,
    "information systems": 1,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 1,
    "machinery": 1,
    "magnetics": 0,
    "maintenance": 1,
    "manufacturing": 7,
    "marketing": 2,
    "materials": 1,
    "mathematics": 3,
    "medical applications": 20,
    "military": 2,
    "mixed reality": 1,
    "mobile computing": 6,
    "operating system": 0,
    "optics": 0,
    "physics": 3,
    "policy": 0,
    "programming language": 3,
    "quality management": 3,
    "risk": 0,
    "robotics": 3,
    "safety": 3,
    "security": 0,
    "sensors": 2,
    "simulation": 5,
    "sustainability": 1,
    "training": 0,
    "transportation": 1,
    "virtual reality": 15,
    "wearables": 6,
    "web services": 0,
    "": ""
  },
  {
    "term": "transportation",
    "accessibility": 2,
    "acoustics": 1,
    "aerospace": 2,
    "artificial intelligence": 6,
    "assembly": 1,
    "augmented reality": 38,
    "automation": 8,
    "automobiles": 8,
    "color": 0,
    "computer vision": 3,
    "computing": 1,
    "construction": 0,
    "control": 1,
    "controllers": 0,
    "data modeling": 1,
    "display technology": 12,
    "education": 2,
    "emergency management": 1,
    "energy management": 0,
    "entertainment": 2,
    "food and agriculture": 0,
    "handheld computing": 1,
    "hardware": 0,
    "holography": 0,
    "human computer interaction": 13,
    "human factors": 8,
    "human resources": 1,
    "image processing": 2,
    "information systems": 2,
    "infrastructure": 11,
    "lighting": 0,
    "location based services": 1,
    "machinery": 0,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 4,
    "marketing": 0,
    "materials": 0,
    "mathematics": 1,
    "medical applications": 1,
    "military": 0,
    "mixed reality": 0,
    "mobile computing": 11,
    "operating system": 0,
    "optics": 0,
    "physics": 0,
    "policy": 0,
    "programming language": 0,
    "quality management": 1,
    "risk": 0,
    "robotics": 2,
    "safety": 0,
    "security": 0,
    "sensors": 0,
    "simulation": 0,
    "sustainability": 0,
    "training": 1,
    "transportation": 0,
    "virtual reality": 7,
    "wearables": 7,
    "web services": 0,
    "": ""
  },
  {
    "term": "virtual reality",
    "accessibility": 18,
    "acoustics": 9,
    "aerospace": 6,
    "artificial intelligence": 29,
    "assembly": 4,
    "augmented reality": 182,
    "automation": 10,
    "automobiles": 4,
    "color": 2,
    "computer vision": 11,
    "computing": 15,
    "construction": 2,
    "control": 10,
    "controllers": 8,
    "data modeling": 14,
    "display technology": 41,
    "education": 14,
    "emergency management": 0,
    "energy management": 1,
    "entertainment": 20,
    "food and agriculture": 6,
    "handheld computing": 8,
    "hardware": 1,
    "holography": 2,
    "human computer interaction": 134,
    "human factors": 65,
    "human resources": 0,
    "image processing": 29,
    "information systems": 8,
    "infrastructure": 3,
    "lighting": 1,
    "location based services": 12,
    "machinery": 7,
    "magnetics": 5,
    "maintenance": 4,
    "manufacturing": 27,
    "marketing": 3,
    "materials": 18,
    "mathematics": 15,
    "medical applications": 66,
    "military": 2,
    "mixed reality": 6,
    "mobile computing": 18,
    "operating system": 0,
    "optics": 6,
    "physics": 10,
    "policy": 0,
    "programming language": 0,
    "quality management": 9,
    "risk": 1,
    "robotics": 12,
    "safety": 5,
    "security": 3,
    "sensors": 8,
    "simulation": 15,
    "sustainability": 11,
    "training": 15,
    "transportation": 7,
    "virtual reality": 0,
    "wearables": 60,
    "web services": 7,
    "": ""
  },
  {
    "term": "wearables",
    "accessibility": 20,
    "acoustics": 6,
    "aerospace": 7,
    "artificial intelligence": 24,
    "assembly": 3,
    "augmented reality": 307,
    "automation": 6,
    "automobiles": 1,
    "color": 4,
    "computer vision": 14,
    "computing": 15,
    "construction": 2,
    "control": 29,
    "controllers": 9,
    "data modeling": 13,
    "display technology": 65,
    "education": 13,
    "emergency management": 0,
    "energy management": 3,
    "entertainment": 23,
    "food and agriculture": 1,
    "handheld computing": 6,
    "hardware": 9,
    "holography": 13,
    "human computer interaction": 137,
    "human factors": 76,
    "human resources": 1,
    "image processing": 30,
    "information systems": 5,
    "infrastructure": 6,
    "lighting": 7,
    "location based services": 15,
    "machinery": 9,
    "magnetics": 2,
    "maintenance": 6,
    "manufacturing": 19,
    "marketing": 3,
    "materials": 25,
    "mathematics": 14,
    "medical applications": 53,
    "military": 1,
    "mixed reality": 8,
    "mobile computing": 40,
    "operating system": 1,
    "optics": 17,
    "physics": 6,
    "policy": 1,
    "programming language": 4,
    "quality management": 14,
    "risk": 1,
    "robotics": 22,
    "safety": 3,
    "security": 2,
    "sensors": 13,
    "simulation": 4,
    "sustainability": 6,
    "training": 6,
    "transportation": 7,
    "virtual reality": 60,
    "wearables": 0,
    "web services": 7,
    "": ""
  },
  {
    "term": "web services",
    "accessibility": 0,
    "acoustics": 0,
    "aerospace": 1,
    "artificial intelligence": 2,
    "assembly": 0,
    "augmented reality": 42,
    "automation": 0,
    "automobiles": 0,
    "color": 0,
    "computer vision": 0,
    "computing": 7,
    "construction": 0,
    "control": 3,
    "controllers": 0,
    "data modeling": 1,
    "display technology": 4,
    "education": 2,
    "emergency management": 1,
    "energy management": 0,
    "entertainment": 2,
    "food and agriculture": 1,
    "handheld computing": 4,
    "hardware": 0,
    "holography": 2,
    "human computer interaction": 20,
    "human factors": 5,
    "human resources": 0,
    "image processing": 3,
    "information systems": 2,
    "infrastructure": 1,
    "lighting": 0,
    "location based services": 4,
    "machinery": 1,
    "magnetics": 0,
    "maintenance": 0,
    "manufacturing": 4,
    "marketing": 3,
    "materials": 0,
    "mathematics": 1,
    "medical applications": 4,
    "military": 1,
    "mixed reality": 0,
    "mobile computing": 12,
    "operating system": 2,
    "optics": 0,
    "physics": 2,
    "policy": 0,
    "programming language": 2,
    "quality management": 4,
    "risk": 0,
    "robotics": 2,
    "safety": 0,
    "security": 2,
    "sensors": 1,
    "simulation": 0,
    "sustainability": 1,
    "training": 0,
    "transportation": 0,
    "virtual reality": 7,
    "wearables": 7,
    "web services": 0,
    "": ""
  }
]

var term = masterList.find(p => p.term === 'web services')

var sortable = [];
for (var vehicle in term) {
    sortable.push([vehicle, term[vehicle]]);
}

var tags = sortable.sort(function(a, b) {
    return a[1] - b[1];
});
